site_name: AWS SAA C03 Notes
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: amber
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: amber
      scheme: slate
      toggle:
        icon: material/weather-light
        name: Switch to dark mode
markdown_extensions:
  - toc:
      permalink: true
  - attr_list