site_name: AWS SAA C03 Notes
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
markdown_extensions:
  - toc:
      permalink: true
  - attr_list
repo_url: https://github.com/vcherx/aws-saa-c03-guide
repo_name: aws-saa-c03-guide